### ISSUE TITLE
Failed to configurate v1.1.0

### ISSUE THREAD

**Issue by Coctus** [warrior25/HA-Nysse#6] opened 2024-02-19 08:34 UTC
Something broke when I installed the latest update of Nysse integration v1.1.0. The integration got "failed to unload" -status. After rebooting the integration started working again but failed to unload again in the middle of night. I tried to reinstall the integration but now I cannot configure it. I have no logs of the failed to unload error but the here's the configuration error and its log.

Error
Config flow could not be loaded: 400: Bad Request

```
Logger: custom_components.nysse.fetch_api
Source: custom_components/nysse/fetch_api.py:37
Integration: Nysse ([documentation](https://github.com/warrior25/HA-Nysse), [issues](https://github.com/warrior25/HA-Nysse/issues))
First occurred: 10:27:46 (1 occurrences)
Last logged: 10:27:46

Failed to fetch stops: 'body'
```

**Comment by warrior25** [comment] 2024-02-19 09:03
I will have a look into this

**Comment by warrior25** [comment] 2024-02-19 11:01
Integration unloading should be fixed in [v.1.1.1](https://github.com/warrior25/HA-Nysse/releases/tag/v.1.1.1). The API providing stops seems to be having some issues, which causes the integration to not work properly right now. There's probably also a need to improve error logging, so that it is clear when errors are caused by Nysse API instead of the integration.

**Closed as completed by warrior25** 2024-02-19 11:01 UTC
